#!/usr/bin/perl

# * This is modified work by Miroslav Madzarevic githubcode@osadmin.com as of May 1st 2002
# * based originally on proxy-2.2.4 program by sparlin@openpro.org

use IO::Socket;

MAIN:
{
  if ($#ARGV != 2) {
	print "Usage: ./regress <proxy server> <port> <# connections>\n"; 
        exit(1);
  }
  for ($i=0;$i<$ARGV[2];$i++) {
    $sd = IO::Socket::INET->new(PeerAddr => $ARGV[0],
				PeerPort => $ARGV[1],
				Proto    => "tcp",
				Type     => SOCK_STREAM)
      or die "Socket: $!";
    
    print $sd "HEAD /index.html HTTP/1.0\n\n";
    print "$i\n";
    while(<$sd>) { print "$_"; }
    
  }
  close($sd);
  
  print "We connected $i times to $ARGV[0]\n";
}
